config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :art_works
  resources :artists
  resources :texts
  resources :authors
  resources :word_of_the_days
  resources :users
  root 'pages#index'
  get "/pages/:contact" => "pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
  has_many :art_works
  validates :name, uniqueness: true, presence: true

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
  before_action :set_artist, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new]
  # GET /artists
  # GET /artists.json
  def index
    @artists = Artist.all
  end

  # GET /artists/1
  # GET /artists/1.json
  def show
  end

  # GET /artists/new
  def new
    @artist = Artist.new
  end

  # GET /artists/1/edit
  def edit
  end

  # POST /artists
  # POST /artists.json
  def create
    @artist = Artist.new(artist_params)

    respond_to do |format|
      if @artist.save
        format.html { redirect_to @artist, notice: 'Artist was successfully created.' }
        format.json { render :show, status: :created, location: @artist }
      else
        format.html { render :new }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /artists/1
  # PATCH/PUT /artists/1.json
  def update
    respond_to do |format|
      if @artist.update(artist_params)
        format.html { redirect_to @artist, notice: 'Artist was successfully updated.' }
        format.json { render :show, status: :ok, location: @artist }
      else
        format.html { render :edit }
        format.json { render json: @artist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /artists/1
  # DELETE /artists/1.json
  def destroy
    @artist.destroy
    respond_to do |format|
      format.html { redirect_to artists_url, notice: 'Artist was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artist
      @artist = Artist.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def artist_params
      params.require(:artist).permit(:name, :bio, :wiki)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_form.html.erb
<%= form_with(model: artist, local: true) do |form| %>
  <% if artist.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artist.errors.count, "error") %> prohibited this artist from being saved:</h2>

      <ul>
      <% artist.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :bio %>
    <%= form.text_area :bio %>
  </div>

  <div class="field">
    <%= form.label :wiki %>
    <%= form.text_field :wiki %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/artists/edit.html.erb
<h1>Editing Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Show', @artist %> |
<%= link_to 'Back', artists_path %>

app/views/artists/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "artists", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>
      </nav>
    </div>
  </header>
<h2>Artists</h2>
<%@artists.each do |artist|%>
<p class="left"><%=link_to artist.name, artist_path(artist)%></p>
<%end%>


  <!-- <main role="main" class="inner cover">


  </main> -->

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>

app/views/artists/new.html.erb
<h1>New Artist</h1>

<%= render 'form', artist: @artist %>

<%= link_to 'Back', artists_path %>

app/views/artists/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "authors", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>
      </nav>
    </div>
  </header>


  <h2><%=@artist.name %></h2>
  <p>Bio: <%= @artist.bio %></p>
  <p>Wiki: <%=link_to @artist.name, @artist.wiki %></p>



  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>


<% if account_signed_in?%>
<p><%= link_to 'Add New Artist', new_artist_path %></p>
<% end %>


<%#link_to 'Edit', edit_artist_path(@artist) %>
<%# link_to 'Back', artists_path %>
<%# link_to 'Home', root_path %>