config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :art_works
  resources :artists
  resources :texts
  resources :authors
  resources :word_of_the_days
  resources :users
  root 'pages#index'
  get "/pages/:contact" => "pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/word_of_the_day.rb
class WordOfTheDay < ApplicationRecord
  has_many :users, through: :user_words
  validates :word, presence: true, uniqueness: true
  validates :definition, presence: true
end

app/controllers/word_of_the_days_controller.rb
class WordOfTheDaysController < ApplicationController
  before_action :set_word_of_the_day, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new]
  # GET /word_of_the_days
  # GET /word_of_the_days.json
  def index
    @word_of_the_days = WordOfTheDay.all
  end

  # GET /word_of_the_days/1
  # GET /word_of_the_days/1.json
  def show
  end

  # GET /word_of_the_days/new
  def new
    @word_of_the_day = WordOfTheDay.new
  end

  # GET /word_of_the_days/1/edit
  def edit
  end

  # POST /word_of_the_days
  # POST /word_of_the_days.json
  def create
    @word_of_the_day = WordOfTheDay.new(word_of_the_day_params)

    respond_to do |format|
      if @word_of_the_day.save
        format.html { redirect_to @word_of_the_day, notice: 'Word of the day was successfully created.' }
        format.json { render :show, status: :created, location: @word_of_the_day }
      else
        format.html { render :new }
        format.json { render json: @word_of_the_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /word_of_the_days/1
  # PATCH/PUT /word_of_the_days/1.json
  def update
    respond_to do |format|
      if @word_of_the_day.update(word_of_the_day_params)
        format.html { redirect_to @word_of_the_day, notice: 'Word of the day was successfully updated.' }
        format.json { render :show, status: :ok, location: @word_of_the_day }
      else
        format.html { render :edit }
        format.json { render json: @word_of_the_day.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /word_of_the_days/1
  # DELETE /word_of_the_days/1.json
  def destroy
    @word_of_the_day.destroy
    respond_to do |format|
      format.html { redirect_to word_of_the_days_url, notice: 'Word of the day was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_word_of_the_day
      @word_of_the_day = WordOfTheDay.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def word_of_the_day_params
      params.require(:word_of_the_day).permit(:word, :definition, :origin, :example, :part_of_speech, :pronunciation)
    end
end

app/helpers/word_of_the_days_helper.rb
module WordOfTheDaysHelper
end

app/views/word_of_the_days/_form.html.erb
<%= form_with(model: word_of_the_day, local: true) do |form| %>
  <% if word_of_the_day.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(word_of_the_day.errors.count, "error") %> prohibited this word_of_the_day from being saved:</h2>

      <ul>
      <% word_of_the_day.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <%= form_for @word_of_the_day do |f| %>
  Word: <%=f.text_field :word %><br>
  Definition: <%=f.text_area :definition %><br>
  Origin: <%=f.text_area :origin %><br>
  Example: <%=f.text_area :example %><br>
  Part of Speech: <%=f.text_field :part_of_speech %><br>
  pronunciation: <%=f.text_area :pronunciation %><br>
    <div class="actions"><br>
      <%= f.submit %>
  </div>
<% end %>
<% end %>

app/views/word_of_the_days/edit.html.erb
<h1>Editing Word Of The Day</h1>

<%= render 'form', word_of_the_day: @word_of_the_day %>

<%= link_to 'Show', @word_of_the_day %> |
<%= link_to 'Back', word_of_the_days_path %>

app/views/word_of_the_days/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "word_of_the_days", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>
      </nav>
    </div>
  </header>
<h2>Word of The Day</h2>

<%@word_of_the_days.each do |word_of_the_day|%>
  <h2><%=link_to word_of_the_day.word, word_of_the_day_path(word_of_the_day) %></h2>
  <p class="left">Definion: <%= word_of_the_day.definition %></p>
  <p class="left">Origin: <%= word_of_the_day.origin %></p>
  <p class="left">Expample Usage: <%= word_of_the_day.example %></p>
  <p class="left">Part of Speech: <%= word_of_the_day.part_of_speech %></p>
  <p class="left">Pronunciation: <%= word_of_the_day.pronunciation %></p>
  <%# link_to 'Show', word_of_the_day %>
  <%# link_to 'Edit', edit_word_of_the_day_path(word_of_the_day) %>
  <%# link_to 'Destroy', word_of_the_day, method: :delete, data: { confirm: 'Are you sure?' } %>
<% end %>


  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>

app/views/word_of_the_days/new.html.erb
<h1>New Word Of The Day</h1>

<%= render 'form', word_of_the_day: @word_of_the_day %>

<%= link_to 'Back', word_of_the_days_path %>

app/views/word_of_the_days/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "word_of_the_days", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>
      </nav>
    </div>
  </header>
<h2>Word of The Day</h2>


  <h2><%=link_to @word_of_the_day.word, word_of_the_day_path(@word_of_the_day) %></h2>
  <p class="left">Definion: <%= @word_of_the_day.definition %></p>
  <p class="left">Origin: <%= @word_of_the_day.origin %></p>
  <p class="left">Expample Usage: <%= @word_of_the_day.example %></p>
  <p class="left">Part of Speech: <%= @word_of_the_day.part_of_speech %></p>
  <p class="left">Pronunciation: <%= @word_of_the_day.pronunciation %></p>
  <%# link_to 'Show', word_of_the_day %>
  <%# link_to 'Edit', edit_word_of_the_day_path(word_of_the_day) %>
  <%# link_to 'Destroy', word_of_the_day, method: :delete, data: { confirm: 'Are you sure?' } %>



  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>




<% if account_signed_in?%>
<p><%= link_to 'Add New Word of the Day', new_word_of_the_day_path %></p>
<% end %>







<!-- <p id="notice"><%# notice %></p>

<h1><%#@word_of_the_day.word %></h1>
<tr>
  <p>Definion: <%# @word_of_the_day.definition %></p>
  <p>Origin: <%# @word_of_the_day.origin %></p>
  <p>Expample Usage: <%# @word_of_the_day.example %></p>
  <p>Part of Speech: <%# @word_of_the_day.part_of_speech %></p>
  <p>Pronunciation: <%# @word_of_the_day.pronunciation %></p> -->
  <%# link_to 'Show', word_of_the_day %>
  <%# link_to 'Edit', edit_word_of_the_day_path(word_of_the_day) %>
  <%# link_to 'Destroy', word_of_the_day, method: :delete, data: { confirm: 'Are you sure?' } %>
</tr>



<%#link_to 'Edit', edit_word_of_the_day_path(@word_of_the_day) %>
<%# link_to 'Back', word_of_the_days_path %> | <%# link_to 'Home', root_path %>