config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :art_works
  resources :artists
  resources :texts
  resources :authors
  resources :word_of_the_days
  resources :users
  root 'pages#index'
  get "/pages/:contact" => "pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/art_work.rb
class ArtWork < ApplicationRecord
  belongs_to :artist
  validates :title, presence: true, uniqueness: true
  validates :image_link, presence: true
end

app/controllers/art_works_controller.rb
class ArtWorksController < ApplicationController
  before_action :set_art_work, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new]
  # GET /art_works
  # GET /art_works.json
  def index
    @art_works = ArtWork.all
  end

  # GET /art_works/1
  # GET /art_works/1.json
  def show
  end

  # GET /art_works/new
  def new
    @art_work = ArtWork.new
  end

  # GET /art_works/1/edit
  def edit
  end

  # POST /art_works
  # POST /art_works.json
  def create
    @art_work = ArtWork.new(art_work_params)

    respond_to do |format|
      if @art_work.save
        format.html { redirect_to @art_work, notice: 'Art work was successfully created.' }
        format.json { render :show, status: :created, location: @art_work }
      else
        format.html { render :new }
        format.json { render json: @art_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /art_works/1
  # PATCH/PUT /art_works/1.json
  def update
    respond_to do |format|
      if @art_work.update(art_work_params)
        format.html { redirect_to @art_work, notice: 'Art work was successfully updated.' }
        format.json { render :show, status: :ok, location: @art_work }
      else
        format.html { render :edit }
        format.json { render json: @art_work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /art_works/1
  # DELETE /art_works/1.json
  def destroy
    @art_work.destroy
    respond_to do |format|
      format.html { redirect_to art_works_url, notice: 'Art work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_art_work
      @art_work = ArtWork.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def art_work_params
      params.require(:art_work).permit(:title, :style, :description, :year, :wiki, :image_link, :artist_id)
    end
end

app/helpers/art_works_helper.rb
module ArtWorksHelper
end

app/views/art_works/_form.html.erb
<%= form_with(model: art_work, local: true) do |form| %>
  <% if art_work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(art_work.errors.count, "error") %> prohibited this art_work from being saved:</h2>

      <ul>
      <% art_work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :style %>
    <%= form.text_field :style %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :year %>
    <%= form.text_field :year %>
  </div>

  <div class="field">
    <%= form.label :wiki %>
    <%= form.text_field :wiki %>
  </div>

  <div class="field">
    <%= form.label :image_link %>
    <%= form.text_field :image_link %>
  </div>

<div class="field">
  Artist: <%=collection_select(:art_work, :artist_id, Artist.all, :id, :name) %>
</div>



  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/art_works/edit.html.erb
<h1>Editing Art Work</h1>

<%= render 'form', art_work: @art_work %>

<%= link_to 'Show', @art_work %> |
<%= link_to 'Back', art_works_path %>

app/views/art_works/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "art_works", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>

      </nav>
    </div>
  </header>
<h2>Art Works</h2>
<% @art_works.each do |art_work| %>

    <h2 ><%= link_to art_work.title, art_work_path(art_work) %></h2>
    <p >Style: <%= art_work.style %></p>
    <p >Description: <%= art_work.description %></p>
    <p >Year: <%= art_work.year %></p>
    <p >Wiki: <%= link_to art_work.wiki, art_work.wiki %></p>
    <td ><%= image_tag(art_work.image_link ) %></td><br><br><br><br><br>
    <td><%# link_to 'Show', art_work %></td>
    <td><%# link_to 'Edit', edit_art_work_path(art_work) %></td>
    <td><%# link_to 'Destroy', art_work, method: :delete, data: { confirm: 'Are you sure?' } %></td>

<% end %>

  <!-- <main role="main" class="inner cover">


  </main> -->

  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>

















<% if account_signed_in?%>
<p><%= link_to 'Add New Art Work', new_art_work_path %></p>
<% end %>

app/views/art_works/new.html.erb
<h1>New Art Work</h1>

<%= render 'form', art_work: @art_work %>

<%= link_to 'Back', art_works_path %>

app/views/art_works/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "art_works", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>
      </nav>
    </div>
  </header>

  <h2 class= "left"><%= @art_work.title %></h2>
  <p class= "left">Style: <%= @art_work.style %></p>
  <p class= "left">Description: <%= @art_work.description %></p>
  <p class= "left">Year: <%= @art_work.year %></p>
  <p class= "left">Wiki: <%= link_to @art_work.wiki, @art_work.wiki %></p>
  <td class= "left"><%= image_tag(@art_work.image_link ) %></td>


  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>

<% if account_signed_in?%>
<p><%= link_to 'Add New Art Work', new_art_work_path %></p>
<% end %>


<%# link_to 'Edit', edit_art_work_path(@art_work) %> |
<%# link_to 'Back', art_works_path %>