config/routes.rb
Rails.application.routes.draw do
  devise_for :accounts
  resources :art_works
  resources :artists
  resources :texts
  resources :authors
  resources :word_of_the_days
  resources :users
  root 'pages#index'
  get "/pages/:contact" => "pages#contact"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/text.rb
class Text < ApplicationRecord
  has_many :users, through: :user_texts
  belongs_to :author
  validates :title, presence: true, uniqueness: true
  validates :content, presence: true
end

app/controllers/texts_controller.rb
class TextsController < ApplicationController
  before_action :set_text, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_account!, only: [:new]
  # GET /texts
  # GET /texts.json
  def index
    @texts = Text.all
  end

  # GET /texts/1
  # GET /texts/1.json
  def show
  end

  # GET /texts/new
  def new
    @text = Text.new
  end

  # GET /texts/1/edit
  def edit
  end

  # POST /texts
  # POST /texts.json
  def create
    @text = Text.new(text_params)

    respond_to do |format|
      if @text.save
        format.html { redirect_to @text, notice: 'Text was successfully created.' }
        format.json { render :show, status: :created, location: @text }
      else
        format.html { render :new }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /texts/1
  # PATCH/PUT /texts/1.json
  def update
    respond_to do |format|
      if @text.update(text_params)
        format.html { redirect_to @text, notice: 'Text was successfully updated.' }
        format.json { render :show, status: :ok, location: @text }
      else
        format.html { render :edit }
        format.json { render json: @text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /texts/1
  # DELETE /texts/1.json
  def destroy
    @text.destroy
    respond_to do |format|
      format.html { redirect_to texts_url, notice: 'Text was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_text
      @text = Text.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def text_params
      params.require(:text).permit(:title, :content, :author_id)
    end
end

app/helpers/texts_helper.rb
module TextsHelper
end

app/views/texts/_form.html.erb
<%= form_with(model: text, local: true) do |form| %>
  <% if text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(text.errors.count, "error") %> prohibited this text from being saved:</h2>

      <ul>
      <% text.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @text do |f| %>
  Title: <%=f.text_field :title %>
  Content: <%=f.text_area :content %>
  Author: <%=collection_select(:text, :author_id, Author.all, :id, :name) %>
    <div class="actions">
      <%= f.submit %>
    </div>
    <% end %>
<% end %>

app/views/texts/edit.html.erb
<h1>Editing Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Show', @text %> |
<%= link_to 'Back', texts_path %>

app/views/texts/index.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "texts", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="#">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>

      </nav>
    </div>
  </header>
<h2>Texts</h2>

<% @texts.each do |text| %>

    <h2><%= link_to text.title, text_path(text)%></h2>
    <p>By: <%= text.author.name %></p>
    <p><%= text.content %></p>
    <!-- <td> link_to 'Show', text </td> -->
    <!-- <td> link_to 'Edit', edit_text_path(text) </td> -->
    <!-- <td> link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } </td> -->

<% end %>


  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>





 <!-- link_to 'New Text', new_text_path  -->
 <%= link_to 'Home', root_path %>

app/views/texts/new.html.erb
<h1>New Text</h1>

<%= render 'form', text: @text %>

<%= link_to 'Back', texts_path %>

app/views/texts/show.html.erb
<!doctype html>
<html lang="en">
  <head>
    <%= stylesheet_link_tag "texts", :media => "all" %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.5">
    <title>Cover Template · Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.3/examples/cover/">

    <!-- Bootstrap core CSS -->
<link href="/docs/4.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <!-- Custom styles for this template -->
    <link href="cover.css" rel="stylesheet">
  </head>
  <body class="text-center">
    <div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="masthead mb-auto">
    <div class="inner">
      <h1 id = "app_title" class="masthead-brand">Litogram</h1>
      <nav class="nav nav-masthead justify-content-center">
        <a id = "nav_butt" class="nav-link active" href="/">Home</a>
        <a id = "nav_butt" class="nav-link active" href="/pages/:contact">Contact</a>
        <a id = "nav_butt" class="nav-link active" href="/art_works">Art</a>
        <a id = "nav_butt" class="nav-link active" href="/texts">Texts</a>
        <a id = "nav_butt" class="nav-link active" href="/word_of_the_days">Word Archive</a>
        <a id = "nav_butt" class="nav-link active" href="/accounts/sign_in">Log In</a>
      </nav>
    </div>
  </header>


  <h2><%=@text.title %></h2>
  <p>By: <%= @text.author.name %></p>
  <p class="left"> <%= @text.content %></p>
  <%# link_to 'Show', word_of_the_day %>
  <%# link_to 'Edit', edit_word_of_the_day_path(word_of_the_day) %>
  <%# link_to 'Destroy', word_of_the_day, method: :delete, data: { confirm: 'Are you sure?' } %>



  <footer class="mastfoot mt-auto">
    <div class="inner">
      <p> Litogram is fast, random, smart, useful stuff to help you pass time. </p>
    </div>
  </footer>
</div>
</body>
</html>




<% if account_signed_in?%>
<p><%= link_to 'Add New Text', new_text_path %></p>
<% end %>








  <!-- <td> link_to 'Show', text </td> -->
  <!-- <td> link_to 'Edit', edit_text_path(text) </td> -->
  <!-- <td> link_to 'Destroy', text, method: :delete, data: { confirm: 'Are you sure?' } </td> -->




<%# <%= link_to 'Edit', edit_text_path(@text) %>
<%# link_to 'Back', texts_path %>
 <%# link_to 'Home', root_path %>